/*
 * This file is generated by jOOQ.
 */
package com.github.topi314.lavasrc.jooq;


import com.github.topi314.lavasrc.jooq.tables.SpotifyTrackMetadata;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in lavasrc.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index SPOTIFY_TRACK_METADATA_SPOTIFY_TRACK_METADATA_ALBUM_ID_IDX = Internal.createIndex(DSL.name("spotify_track_metadata_album_id_idx"), SpotifyTrackMetadata.SPOTIFY_TRACK_METADATA, new OrderField[] { SpotifyTrackMetadata.SPOTIFY_TRACK_METADATA.ALBUM_ID }, false);
    public static final Index SPOTIFY_TRACK_METADATA_SPOTIFY_TRACK_METADATA_ARTIST1_ID_IDX = Internal.createIndex(DSL.name("spotify_track_metadata_artist1_id_idx"), SpotifyTrackMetadata.SPOTIFY_TRACK_METADATA, new OrderField[] { SpotifyTrackMetadata.SPOTIFY_TRACK_METADATA.ARTIST1_ID }, false);
    public static final Index SPOTIFY_TRACK_METADATA_SPOTIFY_TRACK_METADATA_ARTIST2_ID_IDX = Internal.createIndex(DSL.name("spotify_track_metadata_artist2_id_idx"), SpotifyTrackMetadata.SPOTIFY_TRACK_METADATA, new OrderField[] { SpotifyTrackMetadata.SPOTIFY_TRACK_METADATA.ARTIST2_ID }, false);
    public static final Index SPOTIFY_TRACK_METADATA_SPOTIFY_TRACK_METADATA_ARTIST3_ID_IDX = Internal.createIndex(DSL.name("spotify_track_metadata_artist3_id_idx"), SpotifyTrackMetadata.SPOTIFY_TRACK_METADATA, new OrderField[] { SpotifyTrackMetadata.SPOTIFY_TRACK_METADATA.ARTIST3_ID }, false);
    public static final Index SPOTIFY_TRACK_METADATA_SPOTIFY_TRACK_METADATA_ARTIST4_ID_IDX = Internal.createIndex(DSL.name("spotify_track_metadata_artist4_id_idx"), SpotifyTrackMetadata.SPOTIFY_TRACK_METADATA, new OrderField[] { SpotifyTrackMetadata.SPOTIFY_TRACK_METADATA.ARTIST4_ID }, false);
}
