/*
 * This file is generated by jOOQ.
 */
package com.github.topi314.lavasrc.jooq;


import com.github.topi314.lavasrc.jooq.tables.SpotifyTrackMetadata;
import com.github.topi314.lavasrc.jooq.tables.records.SpotifyTrackMetadataRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * lavasrc.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<SpotifyTrackMetadataRecord> KEY_SPOTIFY_TRACK_METADATA_PRIMARY = Internal.createUniqueKey(SpotifyTrackMetadata.SPOTIFY_TRACK_METADATA, DSL.name("KEY_spotify_track_metadata_PRIMARY"), new TableField[] { SpotifyTrackMetadata.SPOTIFY_TRACK_METADATA.ID_SPOTIFY_TRACK_METADATA }, true);
    public static final UniqueKey<SpotifyTrackMetadataRecord> KEY_SPOTIFY_TRACK_METADATA_SPOTIFY_TRACK_METADATA_TRACK_ID_IDX = Internal.createUniqueKey(SpotifyTrackMetadata.SPOTIFY_TRACK_METADATA, DSL.name("KEY_spotify_track_metadata_spotify_track_metadata_track_id_idx"), new TableField[] { SpotifyTrackMetadata.SPOTIFY_TRACK_METADATA.TRACK_ID }, true);
}
