/*
 * This file is generated by jOOQ.
 */
package com.github.topi314.lavasrc.jooq;


import com.github.topi314.lavasrc.jooq.tables.SpotifyTrackMetadata;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Lavasrc extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>lavasrc</code>
     */
    public static final Lavasrc LAVASRC = new Lavasrc();

    /**
     * The table <code>lavasrc.spotify_track_metadata</code>.
     */
    public final SpotifyTrackMetadata SPOTIFY_TRACK_METADATA = SpotifyTrackMetadata.SPOTIFY_TRACK_METADATA;

    /**
     * No further instances allowed
     */
    private Lavasrc() {
        super("lavasrc", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            SpotifyTrackMetadata.SPOTIFY_TRACK_METADATA
        );
    }
}
