/*
 * This file is generated by jOOQ.
 */
package com.github.topi314.lavasrc.jooq;


import com.github.topi314.lavasrc.jooq.tables.SpotifyTrackMetadata;


/**
 * Convenience access to all tables in lavasrc.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>lavasrc.spotify_track_metadata</code>.
     */
    public static final SpotifyTrackMetadata SPOTIFY_TRACK_METADATA = SpotifyTrackMetadata.SPOTIFY_TRACK_METADATA;
}
