/*
 * This file is generated by jOOQ.
 */
package com.github.topi314.lavasrc.jooq.tables.records;


import com.github.topi314.lavasrc.jooq.tables.SpotifyTrackMetadata;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SpotifyTrackMetadataRecord extends UpdatableRecordImpl<SpotifyTrackMetadataRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>lavasrc.spotify_track_metadata.id_spotify_track_metadata</code>.
     */
    public void setIdSpotifyTrackMetadata(Long value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>lavasrc.spotify_track_metadata.id_spotify_track_metadata</code>.
     */
    public Long getIdSpotifyTrackMetadata() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>lavasrc.spotify_track_metadata.album_id</code>.
     */
    public void setAlbumId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>lavasrc.spotify_track_metadata.album_id</code>.
     */
    public String getAlbumId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>lavasrc.spotify_track_metadata.artist1_id</code>.
     */
    public void setArtist1Id(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>lavasrc.spotify_track_metadata.artist1_id</code>.
     */
    public String getArtist1Id() {
        return (String) get(2);
    }

    /**
     * Setter for <code>lavasrc.spotify_track_metadata.artist2_id</code>.
     */
    public void setArtist2Id(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>lavasrc.spotify_track_metadata.artist2_id</code>.
     */
    public String getArtist2Id() {
        return (String) get(3);
    }

    /**
     * Setter for <code>lavasrc.spotify_track_metadata.artist3_id</code>.
     */
    public void setArtist3Id(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>lavasrc.spotify_track_metadata.artist3_id</code>.
     */
    public String getArtist3Id() {
        return (String) get(4);
    }

    /**
     * Setter for <code>lavasrc.spotify_track_metadata.artist4_id</code>.
     */
    public void setArtist4Id(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>lavasrc.spotify_track_metadata.artist4_id</code>.
     */
    public String getArtist4Id() {
        return (String) get(5);
    }

    /**
     * Setter for <code>lavasrc.spotify_track_metadata.track_id</code>.
     */
    public void setTrackId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>lavasrc.spotify_track_metadata.track_id</code>.
     */
    public String getTrackId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>lavasrc.spotify_track_metadata.track_explicit</code>.
     */
    public void setTrackExplicit(Byte value) {
        set(7, value);
    }

    /**
     * Getter for <code>lavasrc.spotify_track_metadata.track_explicit</code>.
     */
    public Byte getTrackExplicit() {
        return (Byte) get(7);
    }

    /**
     * Setter for <code>lavasrc.spotify_track_metadata.track_popularity</code>.
     */
    public void setTrackPopularity(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>lavasrc.spotify_track_metadata.track_popularity</code>.
     */
    public Integer getTrackPopularity() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>lavasrc.spotify_track_metadata.metadata</code>.
     */
    public void setMetadata(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>lavasrc.spotify_track_metadata.metadata</code>.
     */
    public String getMetadata() {
        return (String) get(9);
    }

    /**
     * Setter for <code>lavasrc.spotify_track_metadata.time_created</code>.
     */
    public void setTimeCreated(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>lavasrc.spotify_track_metadata.time_created</code>.
     */
    public Long getTimeCreated() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>lavasrc.spotify_track_metadata.time_updated</code>.
     */
    public void setTimeUpdated(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>lavasrc.spotify_track_metadata.time_updated</code>.
     */
    public Long getTimeUpdated() {
        return (Long) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SpotifyTrackMetadataRecord
     */
    public SpotifyTrackMetadataRecord() {
        super(SpotifyTrackMetadata.SPOTIFY_TRACK_METADATA);
    }

    /**
     * Create a detached, initialised SpotifyTrackMetadataRecord
     */
    public SpotifyTrackMetadataRecord(Long idSpotifyTrackMetadata, String albumId, String artist1Id, String artist2Id, String artist3Id, String artist4Id, String trackId, Byte trackExplicit, Integer trackPopularity, String metadata, Long timeCreated, Long timeUpdated) {
        super(SpotifyTrackMetadata.SPOTIFY_TRACK_METADATA);

        setIdSpotifyTrackMetadata(idSpotifyTrackMetadata);
        setAlbumId(albumId);
        setArtist1Id(artist1Id);
        setArtist2Id(artist2Id);
        setArtist3Id(artist3Id);
        setArtist4Id(artist4Id);
        setTrackId(trackId);
        setTrackExplicit(trackExplicit);
        setTrackPopularity(trackPopularity);
        setMetadata(metadata);
        setTimeCreated(timeCreated);
        setTimeUpdated(timeUpdated);
        resetChangedOnNotNull();
    }
}
